server:
  port: 8080

spring:
  application:
    name: dis-doss-web
  
  cloud:
    function:
      definition: documentCreate;documentUpdate;documentDelete
    stream:
      bindings:
        documentCreate-out-0:
          destination: document-create
          content-type: application/json
        documentUpdate-out-0:
          destination: document-update
          content-type: application/json
        documentDelete-out-0:
          destination: document-delete
          content-type: application/json
        documentCreate-in-0:
          destination: document-create
          group: indexer-group
          content-type: application/json
        documentUpdate-in-0:
          destination: document-update
          group: indexer-group
          content-type: application/json
        documentDelete-in-0:
          destination: document-delete
          group: indexer-group
          content-type: application/json
      rabbit:
        bindings:
          documentCreate-out-0:
            producer:
              exchange: document-exchange
              routing-key: document.create
          documentUpdate-out-0:
            producer:
              exchange: document-exchange
              routing-key: document.update
          documentDelete-out-0:
            producer:
              exchange: document-exchange
              routing-key: document.delete
          documentCreate-in-0:
            consumer:
              exchange: document-exchange
              routing-key: document.create
              durable-subscription: true
          documentUpdate-in-0:
            consumer:
              exchange: document-exchange
              routing-key: document.update
              durable-subscription: true
          documentDelete-in-0:
            consumer:
              exchange: document-exchange
              routing-key: document.delete
              durable-subscription: true
      default:
        consumer:
          max-attempts: 3
          back-off-initial-interval: 1000
  
  # MySQL datasource disabled
  # datasource:
  #   url: jdbc:mysql://localhost:3306/dis-doss?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: root
  #   password: root
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

elasticsearch:
  hosts: localhost:9200
  # Elasticsearch API key for authentication
  api-key: UUNLbE5wb0JKR24yNzR3TE1FNFI6OEV6T3dWMjNLWUM3UTdoM01rRENXdw==

  # JPA disabled (no datasource)
  # jpa:
  #   hibernate:
  #     ddl-auto: none
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQLDialect
  #       format_sql: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    ai.deeprunner.indexer: INFO
    ai.deeprunner.searcher: INFO
    ai.deeprunner.core: INFO
    org.springframework.cloud.stream: INFO

